# Generated by Django 5.2.2 on 2025-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
